/**
 * English -> Urdu. The English text is the key (see lib/i18n.tsx).
 * Keys that are looked up case-insensitively (categories, short team names) are lowercase.
 */
export const UR: Record<string, string> = {
  // ---- navigation / layout
  'Home': 'ہوم',
  'Report a problem': 'مسئلہ رپورٹ کریں',
  'Track complaint': 'شکایت ٹریک کریں',
  'Track a complaint': 'شکایت ٹریک کریں',
  'Officer login': 'افسر لاگ اِن',
  'Officer console': 'افسر کنسول',
  'Citizen site': 'شہری سائٹ',
  'Dashboard': 'ڈیش بورڈ',
  'Complaints': 'شکایات',
  'Escalations': 'ایسکلیشنز',
  'Teams': 'ٹیمیں',
  'Switch to light mode': 'لائٹ موڈ پر جائیں',
  'Switch to dark mode': 'ڈارک موڈ پر جائیں',
  'Aap ki shikayat, hamari zimmedari.': 'آپ کی شکایت، ہماری ذمہ داری۔',
  'A complaint closes only when the problem is truly fixed and verified.': 'شکایت تب ہی بند ہوتی ہے جب مسئلہ واقعی حل اور تصدیق شدہ ہو۔',

  // ---- landing
  'Closed only when it is truly fixed': 'صرف تب بند جب واقعی حل ہو',
  "Your city's problems,": 'آپ کے شہر کے مسائل،',
  'linked to real solutions.': 'حقیقی حل سے جڑے ہوئے۔',
  'Report a broken streetlight, blocked drain or missed garbage pickup. AI agents route it to the right team — and a complaint is only closed after the fix is confirmed.':
    'خراب سٹریٹ لائٹ، بند نالی یا کچرا نہ اٹھنے کی شکایت درج کریں۔ اے آئی ایجنٹس اسے درست ٹیم تک پہنچاتے ہیں — اور شکایت صرف حل کی تصدیق کے بعد بند ہوتی ہے۔',
  'C-1004 · Streetlight, Canal Town': 'C-1004 · سٹریٹ لائٹ، کینال ٹاؤن',
  'Classified: streetlight': 'درجہ بندی: سٹریٹ لائٹ',
  'Priority: Medium · Electrical Dept.': 'ترجیح: درمیانی · محکمہ برقی',
  'Team ELEC-A assigned': 'ٹیم ELEC-A مقرر',
  'Verification failed — still dark': 'تصدیق ناکام — اب بھی اندھیرا',
  'Replanned → Rapid Response Team': 'نئی منصوبہ بندی ← فوری رسپانس ٹیم',
  'Verification passed · Closed': 'تصدیق کامیاب · بند',
  'Complaints this fortnight': 'اس پندرہ دن میں شکایات',
  'Resolved & verified': 'حل شدہ اور تصدیق شدہ',
  'Areas covered': 'احاطہ شدہ علاقے',
  'Zones': 'زونز',
  'How your complaint is handled': 'آپ کی شکایت کیسے نمٹائی جاتی ہے',
  'Six AI agents work in sequence, in seconds. You can watch every step.': 'چھ اے آئی ایجنٹس سیکنڈوں میں ترتیب وار کام کرتے ہیں۔ آپ ہر قدم دیکھ سکتے ہیں۔',
  'STEP': 'مرحلہ',
  'Understands': 'سمجھتا ہے',
  'Reads your complaint and works out what kind of problem it is.': 'آپ کی شکایت پڑھ کر معلوم کرتا ہے کہ مسئلہ کس قسم کا ہے۔',
  'Locates': 'مقام تلاش کرتا ہے',
  'Finds your area and zone. It never guesses a place you did not mention.': 'آپ کا علاقہ اور زون معلوم کرتا ہے۔ جو جگہ آپ نے نہ بتائی ہو اس کا اندازہ نہیں لگاتا۔',
  'Checks duplicates': 'نقل کی جانچ',
  'Spots if neighbours already reported the same issue.': 'دیکھتا ہے کہ کیا پڑوسیوں نے یہی مسئلہ پہلے رپورٹ کیا ہے۔',
  'Sets priority': 'ترجیح طے کرتا ہے',
  'An open manhole near a school comes before a faded road sign.': 'سکول کے قریب کھلا مین ہول، مدھم سڑک کے نشان سے پہلے آتا ہے۔',
  'Picks the department': 'محکمہ چنتا ہے',
  'Routes it to the right department automatically.': 'خود بخود درست محکمے تک پہنچاتا ہے۔',
  'Assigns a team': 'ٹیم مقرر کرتا ہے',
  'Chooses an available team by zone and workload.': 'زون اور کام کے بوجھ کے لحاظ سے دستیاب ٹیم چنتا ہے۔',
  '"Fixed" must be proven': '"حل ہو گیا" ثابت ہونا ضروری ہے',
  'A team saying the job is done is not enough. We check with you. If it is still broken, the complaint is replanned and given to a different team. After repeated failures it goes to a human supervisor — it never just disappears.':
    'ٹیم کا یہ کہنا کافی نہیں کہ کام ہو گیا۔ ہم آپ سے تصدیق کرتے ہیں۔ اگر مسئلہ اب بھی ہے تو شکایت کی نئی منصوبہ بندی ہوتی ہے اور دوسری ٹیم کو دی جاتی ہے۔ بار بار ناکامی پر یہ انسانی سپروائزر کے پاس جاتی ہے — کبھی غائب نہیں ہوتی۔',
  'Try it now': 'ابھی آزمائیں',
  'Team reports the fix': 'ٹیم حل کی رپورٹ دیتی ہے',
  'Citizen feedback is checked': 'شہری کی رائے جانچی جاتی ہے',
  'Not fixed? Replan and reassign': 'حل نہیں ہوا؟ نئی منصوبہ بندی اور نئی ٹیم',
  'Still failing? Escalate to a supervisor': 'اب بھی ناکام؟ سپروائزر کو بھیجیں',

  // ---- submit / track
  'Complaint received': 'شکایت موصول ہو گئی',
  'Save your ID — you can track it any time.': 'اپنی آئی ڈی محفوظ کر لیں — آپ کسی بھی وقت ٹریک کر سکتے ہیں۔',
  'Track page': 'ٹریک صفحہ',
  'New complaint': 'نئی شکایت',
  'Tell us what is wrong. We will find the right team and make sure it is really fixed.': 'ہمیں بتائیں کیا مسئلہ ہے۔ ہم درست ٹیم تلاش کریں گے اور یقینی بنائیں گے کہ مسئلہ واقعی حل ہو۔',
  'What is the problem?': 'مسئلہ کیا ہے؟',
  'e.g. The streetlight in front of my house has not worked since yesterday.': 'مثلاً: میرے گھر کے سامنے سٹریٹ لائٹ کل سے خراب ہے۔',
  'Area': 'علاقہ',
  'Not sure / not listed': 'معلوم نہیں / فہرست میں نہیں',
  'Street / landmark': 'گلی / نشانی',
  'optional': 'اختیاری',
  'Near the main market': 'مرکزی بازار کے قریب',
  'Simulation options': 'سمیولیشن کے اختیارات',
  'Simulated field result': 'فرضی نتیجہ',
  'Real citizen follow-up replaces this later.': 'بعد میں اصل شہری فالو اپ اس کی جگہ لے گا۔',
  'Manual verification': 'دستی تصدیق',
  'Stays open until an officer verifies it': 'افسر کی تصدیق تک کھلی رہتی ہے',
  'A team is assigned. The complaint stays open until an officer verifies the fix.': 'ٹیم مقرر ہو چکی ہے۔ افسر کے حل کی تصدیق تک شکایت کھلی رہے گی۔',
  'Check that the problem is really fixed. The complaint stays open until you confirm it.': 'دیکھیں کہ مسئلہ واقعی حل ہو گیا ہے۔ آپ کی تصدیق تک شکایت کھلی رہے گی۔',
  'Remark (optional)': 'ریمارکس (اختیاری)',
  'Fixed — close complaint': 'حل ہو گیا — شکایت بند کریں',
  'Not fixed — reassign': 'حل نہیں ہوا — دوبارہ تفویض کریں',
  'Fixed first time': 'پہلی بار میں حل',
  'Verification passes immediately': 'تصدیق فوراً کامیاب ہوتی ہے',
  'Fails once, then fixed': 'ایک بار ناکام، پھر حل',
  'Replans and reassigns a new team': 'نئی منصوبہ بندی اور نئی ٹیم',
  'Fails twice, then fixed': 'دو بار ناکام، پھر حل',
  'Two replans before it passes': 'کامیابی سے پہلے دو بار نئی منصوبہ بندی',
  'Never fixed': 'کبھی حل نہیں ہوا',
  'Escalates to a human supervisor': 'انسانی سپروائزر کو بھیج دیا جاتا ہے',
  'Submit complaint': 'شکایت جمع کریں',
  'Agents are processing…': 'ایجنٹس کارروائی کر رہے ہیں…',
  'Agents are working…': 'ایجنٹس کام کر رہے ہیں…',
  'Please describe the problem in a little more detail (at least 10 characters).': 'براہ کرم مسئلہ ذرا تفصیل سے بیان کریں (کم از کم 10 حروف)۔',
  'Something went wrong. Please try again.': 'کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔',
  'Cannot reach the server. Start the backend with "python run.py" and try again.': 'سرور سے رابطہ نہیں ہو سکا۔ بیک اینڈ "python run.py" سے چلائیں اور دوبارہ کوشش کریں۔',
  'Track your complaint': 'اپنی شکایت ٹریک کریں',
  'Enter the complaint ID you received when you reported the problem.': 'مسئلہ رپورٹ کرتے وقت ملنے والی شکایت آئی ڈی درج کریں۔',
  'Complaint ID': 'شکایت آئی ڈی',
  'Track': 'ٹریک',
  'Want to see an example? Try': 'مثال دیکھنا چاہتے ہیں؟ آزمائیں',
  'Looking it up…': 'تلاش کی جا رہی ہے…',
  "We couldn't find": 'ہمیں نہیں ملی',
  'Check the ID and try again. IDs look like C-1234.': 'آئی ڈی چیک کر کے دوبارہ کوشش کریں۔ آئی ڈی کی شکل C-1234 ہوتی ہے۔',
  'Page not found': 'صفحہ نہیں ملا',
  'The page you are looking for does not exist.': 'آپ جو صفحہ تلاش کر رہے ہیں وہ موجود نہیں۔',
  'Back to home': 'ہوم پر واپس',

  // ---- complaint view
  'Problem fixed and confirmed': 'مسئلہ حل ہوا اور تصدیق ہو گئی',
  'The first team could not solve it, so we reassigned it. Closed after {n} attempts.': 'پہلی ٹیم مسئلہ حل نہ کر سکی، اس لیے نئی ٹیم کو دیا گیا۔ {n} کوششوں کے بعد بند۔',
  'Closed after the first verified attempt.': 'پہلی تصدیق شدہ کوشش کے بعد بند۔',
  'Passed to a supervisor': 'سپروائزر کے حوالے',
  'A human officer will take over this complaint.': 'ایک انسانی افسر یہ شکایت سنبھالے گا۔',
  'Work is in progress. We only close a complaint after the fix is confirmed.': 'کام جاری ہے۔ ہم شکایت صرف حل کی تصدیق کے بعد بند کرتے ہیں۔',
  'Copy complaint ID': 'شکایت آئی ڈی کاپی کریں',
  'Possible duplicate': 'ممکنہ نقل',
  'of': 'بابت',
  'Location': 'مقام',
  'Not identified': 'معلوم نہیں ہوا',
  'Department': 'محکمہ',
  'Assigned team': 'مقررہ ٹیم',
  'Not yet assigned': 'ابھی مقرر نہیں',
  'failed attempt': 'ناکام کوشش',
  'failed attempts': 'ناکام کوششیں',
  'What our agents did': 'ہمارے ایجنٹس نے کیا کیا',
  'Every step is recorded so you can see exactly how your complaint was handled.': 'ہر قدم ریکارڈ ہوتا ہے تاکہ آپ دیکھ سکیں آپ کی شکایت کیسے نمٹائی گئی۔',
  'Received': 'موصول',
  'Team assigned': 'ٹیم مقرر',
  'Verifying': 'تصدیق جاری',
  'Closed': 'بند',
  'Escalated': 'ایسکلیٹ',

  // ---- statuses / priorities
  'Verified': 'تصدیق شدہ',
  'Verification failed': 'تصدیق ناکام',
  'Replanning': 'نئی منصوبہ بندی',
  'CLOSED': 'بند',
  'ESCALATED': 'ایسکلیٹ',
  'CRITICAL': 'انتہائی اہم',
  'HIGH': 'زیادہ',
  'MEDIUM': 'درمیانی',
  'LOW': 'کم',
  'pending': 'زیرِ التوا',
  'verified': 'تصدیق شدہ',
  'failed': 'ناکام',

  // ---- admin
  'Last 14 days · sample data for presentation': 'پچھلے 14 دن · پریزنٹیشن کے لیے نمونہ ڈیٹا',
  'Total complaints': 'کل شکایات',
  'Last 14 days': 'پچھلے 14 دن',
  'live': 'لائیو',
  'NEW': 'نئی',
  'In progress': 'جاری',
  'being replanned': 'نئی منصوبہ بندی میں',
  'Closed & verified': 'بند اور تصدیق شدہ',
  'resolution rate': 'حل کی شرح',
  'Need a supervisor': 'سپروائزر درکار',
  'Complaints per day': 'روزانہ شکایات',
  'By category': 'قسم کے لحاظ سے',
  'By priority': 'ترجیح کے لحاظ سے',
  'By zone': 'زون کے لحاظ سے',
  'Open': 'کھلی',
  'Needs attention': 'توجہ درکار',
  'View all': 'سب دیکھیں',
  '{n} of {m} complaints': '{m} میں سے {n} شکایات',
  'Search ID, text, area, team…': 'آئی ڈی، متن، علاقہ، ٹیم تلاش کریں…',
  'All statuses': 'تمام حالتیں',
  'All priorities': 'تمام ترجیحات',
  'All zones': 'تمام زونز',
  'All categories': 'تمام اقسام',
  'No complaints match': 'کوئی شکایت نہیں ملی',
  'Try removing a filter or searching for something else.': 'کوئی فلٹر ہٹا کر یا کچھ اور تلاش کر کے دیکھیں۔',
  'ID': 'آئی ڈی',
  'Problem': 'مسئلہ',
  'Priority': 'ترجیح',
  'Status': 'حالت',
  'Team': 'ٹیم',
  'Submitted': 'جمع کی گئی',
  'retry': 'کوشش',
  'retries': 'کوششیں',
  'Page {n} of {m}': 'صفحہ {n} از {m}',
  'Previous': 'پچھلا',
  'Next': 'اگلا',
  'Back': 'واپس',
  'All complaints': 'تمام شکایات',
  'Complaint not found': 'شکایت نہیں ملی',
  'Agent activity': 'ایجنٹ کی سرگرمی',
  'Classification & location': 'درجہ بندی اور مقام',
  'Category': 'قسم',
  'Subcategory': 'ذیلی قسم',
  'Confidence': 'اعتماد',
  'Zone': 'زون',
  'Location confidence': 'مقام کا اعتماد',
  'Routing': 'روٹنگ',
  'Current team': 'موجودہ ٹیم',
  'Failed teams': 'ناکام ٹیمیں',
  'None': 'کوئی نہیں',
  'Retries': 'کوششیں',
  'Verification': 'تصدیق',
  'Team report': 'ٹیم کی رپورٹ',
  'Citizen feedback': 'شہری کی رائے',
  'Escalation queue': 'ایسکلیشن قطار',
  'Complaints the agents could not close. A human officer must take over.': 'وہ شکایات جو ایجنٹس بند نہ کر سکے۔ انسانی افسر کو سنبھالنا ہوگا۔',
  'Nothing escalated': 'کچھ ایسکلیٹ نہیں ہوا',
  'Every complaint is being handled by the automated workflow.': 'ہر شکایت خودکار ورک فلو کے تحت نمٹائی جا رہی ہے۔',
  'Attempts': 'کوششیں',
  'Reason': 'وجہ',
  'Citizen said': 'شہری نے کہا',
  'Review': 'جائزہ',
  'Verification failed 3 times. A supervisor must take over.': 'تصدیق 3 بار ناکام ہوئی۔ سپروائزر کو سنبھالنا ہوگا۔',
  'No, the problem is still there.': 'نہیں، مسئلہ اب بھی موجود ہے۔',
  'Yes, the problem is solved. Thank you.': 'جی ہاں، مسئلہ حل ہو گیا۔ شکریہ۔',
  'Field teams': 'فیلڈ ٹیمیں',
  'Availability and workload. The assignment agent only picks available teams with spare capacity.': 'دستیابی اور کام کا بوجھ۔ تفویض ایجنٹ صرف وہ ٹیمیں چنتا ہے جو دستیاب ہوں اور گنجائش رکھتی ہوں۔',
  'All departments': 'تمام محکمے',
  'Available': 'دستیاب',
  'Unavailable': 'غیر دستیاب',
  'Workload': 'کام کا بوجھ',
  'tasks': 'کام',

  // ---- places
  'zone': 'زون',
  'University Town': 'یونیورسٹی ٹاؤن',
  'Canal Town': 'کینال ٹاؤن',
  'Tehkal': 'تہکال',
  'Hayatabad': 'حیات آباد',
  'Regi Model Town': 'ریگی ماڈل ٹاؤن',
  'Industrial Estate': 'انڈسٹریل اسٹیٹ',
  'Saddar': 'صدر',
  'Gulbahar': 'گلبہار',
  'Peshawar Cantt': 'پشاور چھاؤنی',
  'Ring Road': 'رنگ روڈ',
  'Warsak Road': 'ورسک روڈ',
  'Charsadda Road': 'چارسدہ روڈ',
  'unknown': 'نامعلوم',

  // ---- categories / subcategories (lowercase: matched case-insensitively)
  'streetlight': 'سٹریٹ لائٹ',
  'road': 'سڑک',
  'water': 'پانی',
  'drainage': 'نکاسیِ آب',
  'garbage': 'کچرا',
  'sanitation': 'صفائی',
  'parks': 'پارکس',
  'sewerage': 'سیوریج',
  'electricity': 'بجلی',
  'other': 'دیگر',
  'streetlight not working': 'سٹریٹ لائٹ خراب',
  'pothole': 'سڑک میں گڑھا',
  'no water supply': 'پانی کی فراہمی بند',
  'blocked drain': 'بند نالی',
  'garbage not collected': 'کچرا نہیں اٹھایا گیا',
  'open manhole': 'کھلا مین ہول',
  'park maintenance': 'پارک کی دیکھ بھال',
  'electrical': 'برقی',
  'roads': 'سڑکیں',
  'general services': 'جنرل سروسز',

  // ---- departments / teams
  'Electrical Department': 'محکمہ برقی',
  'Roads Department': 'محکمہ سڑکیں',
  'Water Department': 'محکمہ پانی',
  'Drainage Department': 'محکمہ نکاسیِ آب',
  'Sanitation Department': 'محکمہ صفائی',
  'Parks Department': 'محکمہ پارکس',
  'Sewerage Department': 'محکمہ سیوریج',
  'General Services Department': 'محکمہ جنرل سروسز',
  'Rapid Response Team': 'فوری رسپانس ٹیم',

  // ---- agents / timeline
  'Classification Agent': 'درجہ بندی ایجنٹ',
  'Location Agent': 'مقام ایجنٹ',
  'History/Duplicate Agent': 'ہسٹری/نقل ایجنٹ',
  'Priority Agent': 'ترجیح ایجنٹ',
  'Department Agent': 'محکمہ ایجنٹ',
  'Assignment Agent': 'تفویض ایجنٹ',
  'Resolution Verification Agent': 'حل کی تصدیق ایجنٹ',
  'Replanning Agent': 'نئی منصوبہ بندی ایجنٹ',
  'Closure Agent': 'اختتامی ایجنٹ',
  'Escalation Agent': 'ایسکلیشن ایجنٹ',
  'Classification completed': 'درجہ بندی مکمل',
  'Location identified': 'مقام کی نشاندہی ہو گئی',
  'Duplicate check completed': 'نقل کی جانچ مکمل',
  'Priority determined': 'ترجیح طے ہو گئی',
  'Department selected': 'محکمہ منتخب',
  'New team assigned': 'نئی ٹیم مقرر',
  'Resolution attempted': 'حل کی کوشش کی گئی',
  'Verification passed': 'تصدیق کامیاب',
  'Complaint closed': 'شکایت بند',
  'Escalated to supervisor': 'سپروائزر کو بھیجی گئی',
  'no duplicate': 'کوئی نقل نہیں',
  'retry {a} of {b}': 'کوشش {a} از {b}',
  'attempt': 'کوشش',
  'citizen feedback': 'شہری کی رائے',
  'reason': 'وجہ',
}
